[TEVA-1292] make the job alert cta sticky to bottom of page
DFE-Digital/teacher-vacancy-service pull request #2055
Opened 2020-09-24 14:20 UTC by alexbowen

https://dfedigital.atlassian.net/browse/TEVA-1292

## Changes in this PR:

this is part one of the Jira task which i am creating PR for so there is a environment for chris to check if he wants to. but this is mergable in it its own right i think

## Screenshots of UI changes:

![Screenshot 2020-09-24 at 15 19 49](https://user-images.githubusercontent.com/1792451/94157708-75425200-fe79-11ea-81ea-d666b4eea090.png)
![Screenshot 2020-09-24 at 15 19 35](https://user-images.githubusercontent.com/1792451/94157717-76737f00-fe79-11ea-99a8-4564dc6397a6.png)

2020-09-25 08:17 UTC, cpjmcquillan approved these changes
Do you want to update the content of the link at the same time?

2020-09-25 09:24 UTC, alexbowen commented
> Do you want to update the content of the link at the same time?

ive changed this to WIP as this PR will have all changes for this task

2020-09-28 09:27 UTC, cpjmcquillan commented on app/views/nqt_job_alerts/new.html.haml
> +    = raw t('terms_and_conditions.read')
We should be able to lose the `raw` and suffix the translation with `_html`

2020-09-28 09:30 UTC, cpjmcquillan commented on app/views/subscriptions/new.html.haml
> +    = raw t('terms_and_conditions.read')
Same as above comment

2020-09-28 09:48 UTC, cpjmcquillan commented on app/views/subscriptions/new.html.haml
> +        [['daily', t('subscriptions.frequency.daily')], ['weekly', t('subscriptions.frequency.weekly')]],
These options should be defined somewhere else probably, maybe on the subscription model as `FREQUENCY_OPTIONS`

2020-09-29 08:42 UTC, cpjmcquillan commented on app/views/subscriptions/new.html.haml
> +      .grouped-text-block
The padding at the top/bottom seems a bit uneven

2020-09-29 08:44 UTC, cpjmcquillan commented on spec/system/job_seekers_can_subscribe_to_a_job_alert_spec.rb
> +      context 'and is redirected to the confirmation page' do
the context should be `when alert frequency is daily` and `when alert frequency is weekly`, and the scenarios `redirects to the confirmation page`

2020-09-29 08:44 UTC, cpjmcquillan commented on spec/system/job_seekers_can_subscribe_to_a_job_alert_spec.rb
> +      context 'and is redirected to the confirmation page' do
https://www.betterspecs.org/

2020-09-29 08:44 UTC, cpjmcquillan approved these changes

2020-09-29 10:20 UTC, david-mears-dfe requested changes

2020-09-29 10:20 UTC, david-mears-dfe commented on app/views/subscriptions/confirm.html.haml
> +        %h2{ class: 'govuk-!-font-size-24' }=t('subscriptions.confirmation.receipt_confirmation', email: @subscription.email)
I believe this font-size is 36 (also for the nqt confirmation page)

2020-09-29 11:36 UTC, merged