[TEVA-1296] add UI to manage filters of a subscription
DFE-Digital/teacher-vacancy-service pull request #2136
Opened 2020-10-14 05:39 UTC by alexbowen

https://dfedigital.atlassian.net/browse/TEVA-1296

![Screenshot 2020-10-14 at 06 35 30](https://user-images.githubusercontent.com/1792451/95948130-e4abc180-0de7-11eb-8447-9c333e6f8ac0.png)
![Screenshot 2020-10-14 at 06 35 46](https://user-images.githubusercontent.com/1792451/95948161-f3927400-0de7-11eb-8cad-425835ef8316.png)

2020-10-14 07:25 UTC, cpjmcquillan commented on app/controllers/subscriptions_controller.rb
> +    @subscription_update_form = SubscriptionForm.new(subscription)
At this point the form needs to take the params as arguments

2020-10-14 07:26 UTC, cpjmcquillan commented on app/controllers/subscriptions_controller.rb
> +    if @subscription_update_form.valid?
Need to add validations on the form for 
- Email presence, email
- Frequency presence
- At least one other field not blank

2020-10-14 07:28 UTC, cpjmcquillan commented on app/controllers/subscriptions_controller.rb
> +      @subscription.update(@subscription_update_form.to_hash)
`@subscription.update` needs to be given a hash like this
```ruby
{ email: 'e@mail.com', frequency: 'weekly', search_criteria: { keyword: 'maths', etc etc } }
```

2020-10-14 07:28 UTC, cpjmcquillan commented on app/controllers/subscriptions_controller.rb
>      @subscription = SubscriptionPresenter.new(subscription)
This and the line above can be in a `before_action` method

2020-10-19 17:42 UTC, cesidio requested changes
There seems to be a bug. When I make a location search for say `London`, and I try to make a new subscription, the keyword takes London too, even though it should just the be location

2020-10-19 18:13 UTC, cpjmcquillan commented
> There seems to be a bug. When I make a location search for say `London`, and I try to make a new subscription, the keyword takes London too, even though it should just the be location

It's because the application doesn't have the LocationPolygons imported

2020-10-20 08:49 UTC, alexbowen commented on app/controllers/subscriptions_controller.rb
> +    ParameterSanitiser.call(params.require(:search_criteria).permit(:keyword, :location, :radius, job_roles: [], phases: [], working_patterns: []))
am i right in thinking this was the part that was making those job_roles etc appear incorrectly on confirmation page?

2020-10-20 09:06 UTC, alexbowen commented
@cpjmcquillan you are a superhero helping me get this over the line 🥇

2020-10-20 13:45 UTC, cesidio approved these changes

2020-10-20 13:50 UTC, merged